# Uncomment the next line to define a global platform for your project
platform :ios, '12.1'

target 'LocalizationHelperDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LocalizationHelperDemo
  pod 'GooglePlaces', '4.1.0'

end
